### ISSUE TITLE
[Typo] November Release: Berserker NPC's Juggernaut refers to Avalanche Charge as just Charge

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#648] opened 2019-12-14 00:39 UTC
**The Problem:**
"When the Berserker uses **Charge**, all characters adjacent to the path they follow or adjacent to their final position – hostile and allied – must succeed on a HULL save or be knocked Prone."

**The Solution:**
"When the Berserker uses **Avalanche Charge**, all characters adjacent to the path they follow or adjacent to their final position – hostile and allied – must succeed on a HULL save or be knocked Prone."

**The Location:**
Page 293

**Comment by KaiTave** [comment] 2019-12-19 01:23
Duplicate of #682

**Closed as completed by KaiTave** 2019-12-19 01:23 UTC
Labels: typo
