### ISSUE TITLE
[Typo] November Release: Extra "said" in Recon SITREP lore

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#643] opened 2019-12-13 17:47 UTC
**The Problem:**
"Attar said **said** as he finished his walkaround of her captured mech."

**The Solution:**
"Attar said as he finished his walkaround of her captured mech."

**The Location:**
Page 273

**Comment by KaiTave** [comment] 2019-12-19 01:27
Duplicate of #685

**Closed as completed by KaiTave** 2019-12-19 01:27 UTC
Labels: typo
