### ISSUE TITLE
[Typo] November Release: Aegis Typo

### ISSUE THREAD

**Issue by LoreLibrarian** [AshleyMoni/Lancer-Community-Edition#515] opened 2019-12-01 08:32 UTC
**The Problem:**
Aegis II: 
E-Defense 3

**The Solution:**
Aegis II:
E-Defense 12

**The Location:**
Pg. 287

**Comment by KaiTave** [comment] 2019-12-01 08:46
Duplicate of #513

**Closed as completed by KaiTave** 2019-12-01 08:46 UTC
