### ISSUE TITLE
[RAI] Clarification on Iskander's Mine Deployer Trait

### ISSUE THREAD

**Issue by KaiTave** [AshleyMoni/Lancer-Community-Edition#59] opened 2019-01-13 05:56 UTC
**The Problem:**
The Iskander's Mine Deployer trait says "When the ISKANDER uses a quick action to plant a mine, it can plant up to 2 other mines in free adjacent spaces as a free action."  Is this meant to be free adjacent spaces to the Iskander itself?  Also, how does this interact with the Assault Launcher?

**The Solution:**
The text of the trait should specify what the freely placed mines are supposed to be adjacent to, and clarification may be needed with regard to how this works in conjunction with the Assault Launcher.

**The Location:**
Pages 273-274

**Comment by Ffzdf** [comment] 2019-01-16 20:53
Confirmed by Tom that mines are placed adjacent to you, bypassing the Assault Launcher.
https://cdn.discordapp.com/attachments/531498621586374656/535199691743166466/Screenshot_20190116-145205.png

**Comment by lenaleciel** [comment] 2019-07-24 02:10
Further text clarification should also probably come with a reminder that mines cannot be placed adjacent to other mines, unless the ability is also intended to overrule that restriction, in which case that should also be clarified.

**Comment by lenaleciel** [comment] 2019-12-05 21:58
Fixed as of November Release.

**Closed** 2019-12-05 22:47 UTC
Labels: rules as intended
