### ISSUE TITLE
[Typo] Lancaster, Combat Repair Window Needs Resized

### ISSUE THREAD

**Issue by CarterRocket** [AshleyMoni/Lancer-Community-Edition#651] opened 2019-12-14 21:32 UTC
**The Problem:**
The Combat Repair feature on the Lancaster window is collapsed and hiding text.

**The Solution:**
The windows needs expanded to show all text for the feature.

**The Location:**
Page 136.

**Comment by KaiTave** [comment] 2019-12-15 00:14
Duplicate of #415 already noted by the editors and fixed.

**Closed as completed by KaiTave** 2019-12-15 00:14 UTC
