### ISSUE TITLE
[RAI] Structure Damage/Reactor Stress and Structure/Overheating Check Clarifications

### ISSUE THREAD

**Issue by Ffzdf** [AshleyMoni/Lancer-Community-Edition#240] opened 2019-06-06 02:11 UTC
**The Problem:**
Structure and Stress are inconsistently referred to across the text as points you take (boxes you check off) vs. points you lose (a bar that depletes to 0). It is also unclear RAW how Atlas and NPCs with max structure/stress less than 4 are meant to roll structure/overheating checks, although Tom has stated how it works for Atlas, which presumably translates to NPCs as well.

**The Solution:**
Make all references to structure loss/damage taken and stress lost/taken consistently either counted up to max or counted down to 0. Personally, I prefer taking structure damage and stress up to the maximum your mech can handle (counting up from 0), which makes rolling for structure/overheating checks more intuitive (roll dice equal to the structure/stress you've taken so far i.e. the number you have written down).

For mechs with less than 4 max structure/stress, simply specify that they roll structure/overheating checks as if they had already taken damage equal to the difference between their max structure/stress and 4. In other words, that they roll extra dice equal to 4 minus their max structure/stress.

This change would necessitate that the structure damage and overheating tables "Direct Hit" and "Meltdown" results instead check the amount of structure/stress you've taken, rather than the amount you have remaining.

**The Location:**
pgs. 117-119, additionally should add structure/overheating check clarification somewhere near the start of the NPC guide.

**Comment by lenaleciel** [comment] 2019-12-05 22:45
Fixed as of the November Release, the Atlas thing got retconned by Tom, and thus the natural reading of the rules (count the damage taken and roll that many, read the table based on the number of structure/stress you have left) is now correct and functioning as intended.

**Closed as completed** 2019-12-19 01:06 UTC
Labels: rules as intended, needs dev input
