### ISSUE TITLE
[Typo] November Release: Typo in "APOCALYPTICA" mission hook

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#637] opened 2019-12-12 21:37 UTC
**The Problem:**
"The new ruler’s opponents have retreated off-world, to a secondary planet where the loyalists the old order make their refuge."

**The Solution:**
"The new ruler’s opponents have retreated off-world, to a secondary planet where the loyalists **of** the old order make their refuge."
**_OR_**
"The new ruler’s opponents have retreated off-world, to a secondary planet where the loyalists **to** the old order make their refuge."

**The Location:**
Page 261

**Comment by KaiTave** [comment] 2019-12-19 02:51
Duplicate of #697

**Closed as completed by KaiTave** 2019-12-19 02:51 UTC
Labels: typo
