### ISSUE TITLE
[Typo] November Release: SSC Sylph Undersuit Typo

### ISSUE THREAD

**Issue by RoosterHogfish** [AshleyMoni/Lancer-Community-Edition#629] opened 2019-12-11 15:46 UTC
**The Problem:**

"These semi-biological, skin-tight undersuits can be
worn for extended periods. They are translucent,
semi-liquid, and **able to be when not in use,**
**confirming** to whatever container they are placed in."

**The Solution:**

"These semi-biological, skin-tight undersuits can be
worn for extended periods. They are translucent,
semi-liquid, and able to be **[MISSING PHRASE]** when not in use,
**conforming** to whatever container they are placed in."

**The Location:**
Top right corner Page 114.  Second paragraph.

**Comment by KaiTave** [comment] 2019-12-19 02:11
Duplicate of #693

**Closed as completed by KaiTave** 2019-12-19 02:11 UTC
Labels: typo
