### ISSUE TITLE
[Typo] November Release: Ace NPC's Bombing Bay missing blast icon

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#646] opened 2019-12-14 00:10 UTC
**The Problem:**
"This causes a 1 explosion that must at overlap with at least 1 space occupied by their target."

**The Solution:**
"This causes a **[blast AoE icon]** 1 explosion that must at overlap with at least 1 space occupied by their target." Basing the AoE icon used based on the PRv2 version of this system, which specifies blast.

**The Location:**
Page 286

**Comment by KaiTave** [comment] 2019-12-19 01:24
Duplicate of #683

**Closed as completed by KaiTave** 2019-12-19 01:24 UTC
Labels: typo
