### ISSUE TITLE
[Typo] Berserker typo

### ISSUE THREAD

**Issue by RoosterHogfish** [AshleyMoni/Lancer-Community-Edition#642] opened 2019-12-13 16:18 UTC
**The Problem:**
Beserker fluff text is missing first part of description.

"their weapon output by orders of magnitude. The archetype, best-known for
its use by Gen’Dal Merlos’s Knights of Imminent Destruction, is preferred
by pure combat-focus organizations, PMCs, and deniable-asset corps in
established states."

**The Solution:**
Add in missing text or re-write

**The Location:**
Top of page 293

**Comment by KaiTave** [comment] 2019-12-13 22:51
Duplicate of #552 which has been noted as fixed by Jay.

**Closed as completed by KaiTave** 2019-12-13 22:51 UTC
