### ISSUE TITLE
[RAI][December Release] OASIS Wall is too short on Dusk Wing

### ISSUE THREAD

**Issue by Plastic1d3** [AshleyMoni/Lancer-Community-Edition#705] opened 2019-12-19 03:50 UTC
**The Problem:**
The Dusk Wing's OASIS wall is now "size of mech" instead of size 1. This was likely to make the system more useful for size 2+ mechs, but it has the effect of making size 1 allies of a Dusk Wing with the system unable to use the cover provided

**The Solution:**
Should be "mech's size, rounded up" I think

**The Location:**
Page 171

**Comment by KaiTave** [comment] 2019-12-19 03:54
Duplicate of #706

**Closed as completed** 2019-12-19 03:55 UTC
