### ISSUE TITLE
[RAI] November Release: "Clear all heat" effects, the Fuel Rod Gun and the Restock Drone

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#561] opened 2019-12-03 22:20 UTC
**The Problem:**
Certain effects, such as the Sherman's Mathur Stop trait and the Genghis's Explosive Vents have been changed to trigger when you "clear all heat," while the Fuel Rod Gun from Nuclear Cavalier and the Lancaster's Restock Drone have been changed to say "clear (some amount) Heat" thus suggesting that they trigger both Mathur Stop and Explosive Vents when you manage to clear all your heat with the Fuel Rod Gun or Restock Drone. In previous editions, the Fuel Rod Gun was explicitly referred to as not counting as cooling and the Restock Drone was ambiguous.  (See https://github.com/AshleyMoni/Lancer-Community-Edition/issues/206)

**The Solution:**
Check with Tom to see if this is an intentional change. Note that this leads to strange behavior like the fuel rod gun being able to jump a sherman from 1 heat to the Danger Zone, which might not be intended, but probably isn't broken.

**The Location:**
Mathur Stop pg 246
Explosive Vents pg 232
Fuel Rod Gun pg 99
Restock Drone pg 138

**Comment by KaiTave** [comment] 2019-12-19 01:45
Duplicate of #689

**Closed as completed by KaiTave** 2019-12-19 01:45 UTC
Labels: rules as intended, needs dev input
