### ISSUE TITLE
[Typo] November Release: Regular Move should be Standard move

### ISSUE THREAD

**Issue by liq3** [AshleyMoni/Lancer-Community-Edition#658] opened 2019-12-18 05:22 UTC
**The Problem:**
There's 4 places in the book that refer to a "regular move". I'm pretty sure they should say "standard move". 

**The Solution:**
Change regular to standard. 

**The Location:**
Assassin's Kai Bioplating, pg 289
Mirage's Reality Flicker, pg 304
Operator's Trace Drive, pg 306
Extraction Sitrep, under "objective", pg 270

**Comment by KaiTave** [comment] 2019-12-19 01:11
Duplicate of #675

**Closed as completed by KaiTave** 2019-12-19 01:11 UTC
Labels: typo
