### ISSUE TITLE
[Typo] November Release: Typo in Iterative Worldbuilding intro

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#644] opened 2019-12-13 20:07 UTC
**The Problem:**
"The second is to show you **theworlds** we envision exist in the world of LANCER, to give you an idea for creating your own unique worlds and landscapes."

**The Solution:**
"The second is to show you **the worlds** we envision exist in the world of LANCER, to give you an idea for creating your own unique worlds and landscapes."

**The Location:**
Page 274

**Comment by KaiTave** [comment] 2019-12-19 01:26
Duplicate of #684

**Closed as completed by KaiTave** 2019-12-19 01:26 UTC
Labels: typo
