### ISSUE TITLE
[Typo] November Release: Assassin NPC's Heat Capacity

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#640] opened 2019-12-13 05:05 UTC
**The Problem:**
The Assassin NPC's Heat Capacity goes from 7 at tier 1 to 8 at tier 2 to back to 7 at tier 3.

**The Solution:**
The pr2 version of the text had it stay consistently at 7 at all tiers.

**The Location:**
Assassin, pg 289

**Comment by KaiTave** [comment] 2019-12-19 02:53
Duplicate of #700

**Closed as completed by KaiTave** 2019-12-19 02:53 UTC
Labels: typo
