### ISSUE TITLE
[Typo] November Release: Role icon size inconsistent in NPC section

### ISSUE THREAD

**Issue by Koleos4** [AshleyMoni/Lancer-Community-Edition#569] opened 2019-12-04 01:55 UTC
**The Problem:**
The role icons in the NPC section vary in size. The Size 4 icon for Squad specifically also appears to be too small.

**The Solution:**
Not even sure if this is a Big Problem, but making them consistent would be the fix.

**The Location:**
Pages 286 through 323,  most easily visible on 289-290, 296-297, and 302-303.

**Comment by Koleos4** [comment] 2019-12-04 01:57
I briefly scanned through the PC mechs in the compendium and it does not appear to be a problem there, but probably best to double-check all the same.

**Comment by KaiTave** [comment] 2019-12-19 01:48
Duplicate of #690 (nice)

**Closed as completed by KaiTave** 2019-12-19 01:48 UTC
Labels: typo
