### ISSUE TITLE
[Typo] pg 341 little warsto

### ISSUE THREAD

**Issue by stmustachio** [AshleyMoni/Lancer-Community-Edition#523] opened 2019-12-01 17:17 UTC
**The Problem:**
> at the conclusion of the Little Warsto pledge  peace.

**The Solution:**

> at the conclusion of the Little Wars to pledge  peace.

**The Location:**
Pg 341 top right of page first paragraph second column

**Comment by KaiTave** [comment] 2019-12-01 20:54
Duplicate of #424

**Closed as completed by KaiTave** 2019-12-01 20:54 UTC
