### ISSUE TITLE
[Typo] November Release: Ambiguity in trigger to Berserker NPC's Superhot reaction

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#649] opened 2019-12-14 00:49 UTC
**The Problem:**
"Trigger: The Berserker takes damage **in melee**." "In melee" isn't a game-defined term, and thus is a bit ambiguous as to whether this reaction:
 -Can be done in response to an attack done within the Berserker's Threat (including ranged attacks)
 -Can be done to someone dealing a ranged attack to the Berserker well out of its threat, as long as someone is engaged with the Berserker
 Etc., etc.

**The Solution:**
"Trigger: The Berserker takes damage **from a melee attack**."
OR
"Trigger: The Berserker takes **melee attack** damage."

The latter sounds more awkward and isn't as tight, but it can save some precious real estate if that's an issue. I'm assuming the intent is based off how this worked as "Molten Shield" in PRv2.

**The Location:**
Page 293

**Comment by KaiTave** [comment] 2019-12-14 02:33
"The Berserker takes damage from a melee attack" is in line with the PRv2 wording so that would be my suggestion as well.

**Comment by KaiTave** [comment] 2019-12-19 01:22
Duplicate of #681

**Closed as completed by KaiTave** 2019-12-19 01:22 UTC
Labels: typo
