### ISSUE TITLE
[Typo], Pilot Gear tags

### ISSUE THREAD

**Issue by kafzeil** [AshleyMoni/Lancer-Community-Edition#823] opened 2020-01-14 00:58 UTC
Problem: Two of the tags in Corrective are much darker font color, bordering on unreadable

The Solution: Switching these tags to white as intended should improve readability

Location:
Page 112, Top left box

**Comment by KaiTave** [comment] 2020-01-14 01:02
Duplicate of #807

**Closed as completed by KaiTave** 2020-01-14 01:02 UTC
Labels: typo
