### ISSUE TITLE
[Typo] November Release: Assault Hardsuit description starts under the Hardsuit table

### ISSUE THREAD

**Issue by VertigoCharades** [AshleyMoni/Lancer-Community-Edition#425] opened 2019-11-28 00:26 UTC
**The Problem:**
The first line of the Assault Hardsuit description is buried underneath the table instead of starting in the next column.

**The Solution:**
Have the description start in the next column of text.

**The Location:**
Page 110

**Comment by Techhead0** [comment] 2019-11-28 02:11
Duplicate of #389

**Closed as completed** 2019-11-28 19:14 UTC
Labels: typo
