### ISSUE TITLE
[Typo] AI Description text duplication

### ISSUE THREAD

**Issue by dwarf74** [AshleyMoni/Lancer-Community-Edition#547] opened 2019-12-02 15:05 UTC
**The Problem:**
There are what looks like two versions of the same paragraph on the bottom of the left text column, flowing to the top of the right text column. (Both paragraphs begin with "Shackled NHPs".) The full text of each is different, but they hit on most of the same points with slightly different wording.

**The Solution:**
Consolidate the two paragraphs.

**The Location:**
pg 107

**Comment by VertigoCharades** [comment] 2019-12-02 17:40
This seems to be a duplicate of the now-closed #420 (nice) ticket

**Closed as completed** 2019-12-02 21:29 UTC
