### ISSUE TITLE
[RAI] Burst Rule Confusion & Inconsistency

### ISSUE THREAD

**Issue by Luciferos** [AshleyMoni/Lancer-Community-Edition#752] opened 2019-12-24 17:45 UTC
**The Problem:**
There's a discrepancy between Burst wording on pages 64 and 104.  It'd be easy for players and GMs to refer to one section and never notice that a separate block for the same rule on a different page has extra rule. Specifically, p.64 has updated Burst to include the spaces the Burst originates in (for effects like Mines, or Atlas occupying an enemy space and using a Flechette Launcher, etc, so that your Burst effects don't completely ignore enemies who are in the space of the Burst. However, p.104 is not updated to reflect this.

Furthermore, the old, clear wording that made Bursts a radius drawn AROUND the originating character is gone; it now says it's centered on an originator's 'space', which obfuscates for newer players and GMs how the radius is drawn. I.E., if a Size 3 target originates a Burst 1, does it only affect the 7 spaces they occupy, due to being a radius drawn from their center?

Burst should be reworded to invoke that it affects the originating character's spaceS and a radius X around them, and the p.64 and 104 wording should be unified.

P.64
![image](https://user-images.githubusercontent.com/20429868/71421466-fd749c00-2648-11ea-9f53-40f5bc793665.png)

P.104
![image](https://user-images.githubusercontent.com/20429868/71421474-0d8c7b80-2649-11ea-9cd5-7ddb296cd736.png)

**The Solution:**

>BURST X: Affects characters within the space(s) occupied by the user (or target) of the BURST, as well as characters in radius X around their space(s). If the BURST is an attack, the user/target is not affected, unless specified. Cover and line of sight are calculated from the user/target. If a BURST effect is ongoing, it moves with the user/target it originates from.

Maybe you can find better wording, but the above wording is as succinct and should cover all instances in the book; a Mine, for example, now affects its originating space (but not itself, not that this matters); a Flechette Launcher or Stuncrown hits enemies in the space occupied by the user, but not the user; an Annihilator's Burst component does not hit the target struck by its attack, which is intended; Aegis and ICEOUT drones clearly affect themselves.

**Comment by lenaleciel** [comment] 2019-12-24 17:52
Duplicate of #692, which appears to be fixed, though not present in the latest release (it appears to have been posted and resolved on the Thursday after the latest paid update)

**Comment by KaiTave** [comment] 2019-12-25 04:53
Closed, per Jay.

**Closed as completed by KaiTave** 2019-12-25 04:53 UTC
