### ISSUE TITLE
[RAI] November Release: Manticore Sear only works on Engaged targets, which is now defined as hostile only.

### ISSUE THREAD

**Issue by darloth** [AshleyMoni/Lancer-Community-Edition#564] opened 2019-12-04 00:18 UTC
**The Problem:**
Originally the Manticore's Sear ability (page 212) was worded to trigger specifically on targets in adjacency or engaged with the target, adding +2 heat to a maximum of 6 to the target.  It now specifically only mentions things engaged with the target, and Engagement has been defined as being hostile targets only.

Since Summon, one of the Manticore's other license abilities, involves bringing characters close together to a target, there was a clear synergy that you could Summon and then Sear to increase heat significantly, assuming you succeeded on the rolls and were willing to absorb Sear's self damage.  This is no longer possible.

**The Solution:**
We need to know whether this change is intentional.  If it is intentional, Sear's self-damage may need to be reduced as it is by no means as easy to trigger, especially considering Beckon has had self-damage added.

**The Location:**
Page 212.  Also see page 62 where Engagement is defined.  Also get mildly upset that Engagement is not defined on page 77 where it ought to be defined.

**Comment by KaiTave** [comment] 2019-12-04 00:23
Duplicate of #563

**Closed as completed by KaiTave** 2019-12-04 00:23 UTC
