### ISSUE TITLE
[Typo] November Release: "See Below" note in last line

### ISSUE THREAD

**Issue by Prem-Sinha** [AshleyMoni/Lancer-Community-Edition#653] opened 2019-12-15 06:44 UTC
**The Problem:**
The section on Repairs and Rest occupies the left side column of the page by itself. The very last line of the last note tells the reader to "see below", but the relevant section, Destroyed Mechs, is actually the first thing in the right side column.

> They may also spend REPAIRS at the following costs:
>• 1 REPAIR: Restore full HP, or repair a destroyed
weapon or system.
>• 2 REPAIRS: Restore 1 STRUCTURE or 1 STRESS.
>• 4 REPAIRS: Repair a destroyed mech (see below).

**The Solution:**
The _"see below"_ note could be replaced with _"see next section"_.
Other options are "see next column", "see next", "see right", etc.

**The Location:**
Page 82
Mech Combat, Wear and Tear

**Comment by KaiTave** [comment] 2019-12-19 01:16
Duplicate of #678

**Closed as completed by KaiTave** 2019-12-19 01:16 UTC
Labels: typo
